name: eic7700-image

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  ARCH: riscv

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Update Apt Cache
        run: sudo apt update

      - name: Install Software
        run: |
              sudo apt install -y git snapd qemu-user-static ubuntu-dev-tools zstd
              sudo systemctl restart systemd-binfmt
              sudo snap install --classic ubuntu-image

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        run: |
              sudo snap run ubuntu-image --workdir workdir --debug classic image-definition.yaml
              pushd workdir
                sudo zstd *.img
              popd

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: eic7700-image-2025.07
          path: workdir/*.zst
          retention-days: 30
